import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { NextAuthProvider } from "@/components/Provider";
import { Toaster } from "react-hot-toast";
import PathnameLayout from "@/components/layout/PathnameLayout";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} dark:bg-medium dark:text-white`}
      >
        <NextAuthProvider>
          <PathnameLayout>
            <div className="flex-auto">{children}</div>
            <Toaster position="top-center" />
          </PathnameLayout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
